Minor Cleanup of Structured Logging Module
dbt-labs/dbt-core pull request #4266
Opened 2021-11-10 19:44 UTC by nathaniel-may

### Description

Cleaned up some of the code.

### Checklist

- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change

2021-11-11 01:23 UTC, leahwicz approved these changes

2021-11-15 16:47 UTC, emmyoop approved these changes
Love how much cleaner it is.

2021-11-16 15:28 UTC, emmyoop approved these changes
The adapter fixes you implemented made me realize we should have generic adapter types, similar to what's in `test_types.py` for new adapters(or anyone inclined to make more updates than the few lines).  Seems off to have new adapters use the old logging format.

2021-11-16 16:09 UTC, iknox-fa requested changes
Just swap to using the built-in get method on those dicts and 👍

2021-11-16 16:12 UTC, nathaniel-may commented
@emmyoop if I'm understanding you correctly, I think that's exactly what we have already with the subclasses of `types.py::AdapterEventBase`. Do you mean something different than that?

2021-11-16 21:24 UTC, iknox-fa reviewed
LGTM!

2021-11-16 22:30 UTC, emmyoop approved these changes

2021-11-17 01:19 UTC, iknox-fa approved these changes

2021-11-17 01:22 UTC, merged