updating contributing.md based on suggestions from updates to adapter…
dbt-labs/dbt-core pull request #4356
Opened 2021-11-29 20:14 UTC by McKnight-42

… contributing files.

resolves #

### Description

Updating terminology used in Contributing.md to match that of other repos to speak more explicitly. 
ex. `dbt` -> `dbt-core` 

removed references to Python 3.6.

rename `develop` to `main` in docs regarding trunk name

### Checklist

- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change

2021-11-29 22:56 UTC, kwigley requested changes

2021-11-29 22:56 UTC, kwigley commented on CONTRIBUTING.md
> +- A maintainer will need to add the `ok to test` label, at which point your subsequent commits will trigger integration tests in BigQuery.
```suggestion
```

2021-11-29 22:56 UTC, kwigley commented on CONTRIBUTING.md
> +The `dbt-core` maintainers use labels to categorize open issues. Some labels indicate the databases impacted by the issue, while others describe the domain in the `dbt-core` codebase germane to the d
```suggestion
The `dbt-core` maintainers use labels to categorize open issues. Most labels describe the domain in the `dbt-core` codebase germane to the discussion.
```

2021-12-03 16:14 UTC, kwigley reviewed
looks good! left one suggestion

2021-12-03 16:14 UTC, kwigley commented on CONTRIBUTING.md
> +To confirm you have correct version of dbt installed please run `dbt --version` and `which dbt`
```suggestion
```
Looks like we mention this in the "Running `dbt-core`" section, not sure if it is necessary.

2021-12-03 16:14 UTC, kwigley approved these changes

2021-12-10 01:06 UTC, leahwicz approved these changes

2021-12-10 19:14 UTC, merged