Add defer to docs and compile commands
dbt-labs/dbt-core pull request #4514
Opened 2021-12-18 10:09 UTC by kadero

resolves #4110 #3741

### Description

### Checklist

- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change

2022-02-14 15:53 UTC, ChenyuLInx commented
Thanks for contributing this @kadero! Sorry for getting back to you late. Can we add some tests to validate the added functionality?

2022-02-24 14:55 UTC, kadero commented
> Thanks for contributing this @kadero! Sorry for getting back to you late. Can we add some tests to validate the added functionality?

Hi @ChenyuLInx, 
Thanks for your message :slightly_smiling_face:,
I will work on those tests on it in the next few days :+1:

2022-03-14 18:51 UTC, kadero commented
> > Thanks for contributing this @kadero! Sorry for getting back to you late. Can we add some tests to validate the added functionality?
> 
> Hi @ChenyuLInx, Thanks for your message slightly_smiling_face, I will work on those tests on it in the next few days +1

@ChenyuLInx done :heavy_check_mark:

2022-03-14 19:41 UTC, ChenyuLInx commented
> @ChenyuLInx done ✔️
Thanks for adding the tests!! One question regarding this test and the one you added for the snapshot. Is there any way that we can validate one step further that the defer actually used the previous state?(Looks like it did since without providing the previous state, the run would fail) Maybe we can validate more things returned in the defer run?

Also I should have noticed it the first time but as I was going over Jeremy's comment in #4110, seems like we can 
* Move `defer_to_manifest` up from RunTask into [CompileTask](https://github.com/dbt-labs/dbt-core/blob/f79a968a0908add9de1b6acfdb75a6b205134ebd/core/dbt/task/compile.py#L36) (its parent)

With this change you put in right? that would make things cleaner?

2022-03-17 08:28 UTC, kadero commented
> > @ChenyuLInx done heavy_check_mark
> > Thanks for adding the tests!! One question regarding this test and the one you added for the snapshot. Is there any way that we can validate one step further that the defer actually used the previous state?(Looks like it did since without providing the previous state, the run would fail) Maybe we can validate more things returned in the defer run?
> 
> Also I should have noticed it the first time but as I was going over Jeremy's comment in #4110, seems like we can
> 
> * Move `defer_to_manifest` up from RunTask into [CompileTask](https://github.com/dbt-labs/dbt-core/blob/f79a968a0908add9de1b6acfdb75a6b205134ebd/core/dbt/task/compile.py#L36) (its parent)
> 
> With this change you put in right? that would make things cleaner?

Hi @ChenyuLInx :wave:,

Thank you for your comment. It's done :heavy_check_mark: `defer_to_manifest` is moved to CompileTask.

Please tell me if something is missing in this PR :slightly_smiling_face:

:pray:

2022-03-22 20:39 UTC, ChenyuLInx requested changes
Hey @kadero , sorry for getting back late! Thanks for moving the previous part code around. I somehow missed to add the two comments I added this time. Can we be a bit more specific on the tests so that it doesn't only check that we can provide defer command but also check that defer works as expected under the hood.

2022-03-22 20:39 UTC, ChenyuLInx commented on test/integration/029_docs_generate_tests/test_docs_generate.py
> +        results = self.run_dbt(['docs', 'generate', '--state', 'state', '--defer'])
Same here, can we check different behavior of defer vs no defer?

2022-07-14 15:00 UTC, katieclaiborne commented
Is there a similar issue related to the `dbt ls` command?

2022-07-31 04:17 UTC, ChenyuLInx commented
> Is there a similar issue related to the `dbt ls` command?

@katieclaiborne  Sorry for getting back to you late. Are you asking that is there an issue related to also adding defer for `ls` command?

2022-07-31 08:26 UTC, kadero commented on test/integration/062_defer_state_tests/test_defer_state.py
> +        self.run_dbt(['compile', '--state', 'state', '--defer'])
Added :heavy_check_mark:. Please tell me @ChenyuLInx if you want to assert something more specific.

:pray:

2022-08-01 13:26 UTC, katieclaiborne commented
> Are you asking that is there an issue related to also adding defer for ls command?

Yes, exactly!

2022-08-01 21:37 UTC, ChenyuLInx approved these changes
Looks good to me! @kadero  thanks for adding this and the test!

2022-08-01 21:38 UTC, merged

2022-08-01 21:39 UTC, ChenyuLInx commented
> > Are you asking that is there an issue related to also adding defer for ls command?
> 
> Yes, exactly!

@katieclaiborne  I don't think so, feel free to open an issue about it!

2022-08-03 13:55 UTC, katieclaiborne commented
Oops, I just realized that this is already possible with [the state method](https://docs.getdbt.com/reference/node-selection/methods#the-state-method)!