Get more information on error
dbt-labs/dbt-core pull request #4767
Opened 2022-02-23 16:14 UTC by gshank

resolves #

Testing instrumentation to diagnose error on Windows run.

### Description

### Checklist

- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change

2022-02-23 18:56 UTC, gshank commented
Tests didn't fail. Also not failing on main now.

2022-02-24 23:01 UTC, emmyoop requested changes
One small request to document why we're doing this for future us.  Could also be worth starting a README with the reasons we do unexpected things.

2022-02-25 15:56 UTC, gshank commented on core/dbt/tests/fixtures/project.py
> +                fp.write(data)
Excellent idea, and much more readable. Have created 'read_file' and 'write_file' functions.

2022-02-25 16:01 UTC, emmyoop approved these changes

2022-02-25 16:01 UTC, emmyoop commented on core/dbt/tests/util.py
> +# Windows we'll get codepage 1252 and things might break
🎉

2022-02-25 16:13 UTC, merged