Er/ct 303 004 simple snapshot
dbt-labs/dbt-core pull request #4838
Opened 2022-03-07 20:54 UTC by emmyoop

resolves #

### Description

WIP 004 test conversion

### Checklist

- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change

2022-03-09 20:11 UTC, ChenyuLInx commented on tests/functional/simple_snapshot/test_basic_snapshot.py
> +    def test_basic_ref(project, basic_ref):
If the mark.usefixtures("project") is stated for the whole calss, is the project fixture here still needed?

2022-03-09 20:16 UTC, ChenyuLInx commented on tests/functional/simple_snapshot/test_slow_query_snapshot.py
> +def test_slow(project):
Do we still need this one?

2022-03-09 22:09 UTC, gshank commented
Fixtures shouldn't be used for executing tests. They are intended to be used only for setting up the data/project necessary for executing tests. I'm going to take a deeper look and see if I can come up with some suggestions for how to do it.

2022-03-09 22:40 UTC, gshank commented
A bunch of the tests fail when doing `pytest -v tests/functional/simple_snapshot`

2022-03-10 19:59 UTC, gshank requested changes

2022-03-10 23:11 UTC, gshank approved these changes
Looks good!

2022-03-11 20:52 UTC, merged