lower networkx for py37 (#5264)
dbt-labs/dbt-core pull request #5373
Opened 2022-06-14 23:31 UTC by ChenyuLInx

Backport (#5264)(cherry picked from commit a5993fc866bbc6467625342914ed9a47e90ec677)

resolves #

### Description

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

2022-06-14 23:33 UTC, ChenyuLInx commented
Changed upper limit to include @jtcohen6 's recent change for requirements

2022-06-16 10:09 UTC, jtcohen6 approved these changes

2022-06-16 10:10 UTC, jtcohen6 requested changes
Actually - do you mind adding a quick Changelog entry for this, under the `Dependencies` category? Since it will be included in 1.1.2

2022-07-05 19:03 UTC, iknox-fa approved these changes
LGTM

2022-09-12 17:20 UTC, closed without merging