[CT-679] flip logic around reset color detection
dbt-labs/dbt-core pull request #5394
Opened 2022-06-17 20:00 UTC by darin-reify

- this makes is so that the reset color code won't be appended to logs
  when `use-colors` is false.

resolves #5288

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

2022-06-22 13:54 UTC, gshank commented
Darin: Can you sign one of the CLAs which is linked from https://docs.getdbt.com/docs/contributing/contributor-license-agreements?  We can get this processed once that's done. Thanks!

2022-06-22 16:22 UTC, darin-reify commented
> Darin: Can you sign one of the CLAs which is linked from https://docs.getdbt.com/docs/contributing/contributor-license-agreements? We can get this processed once that's done. Thanks!

hey there, sorry was just crossing my t's and dotting my i's. i've signed the agreement!

2022-06-22 17:52 UTC, gshank requested changes

2022-06-22 17:52 UTC, gshank commented on core/dbt/events/functions.py
> +    color_tag: str = "" if not this.format_color else Style.RESET_ALL
We need the same change in the 'create_info_text_log_line' function at about line 170.

2022-06-29 21:27 UTC, gshank approved these changes

2022-06-29 21:28 UTC, merged