Add changelog and whitespace fix to version bump Action
dbt-labs/dbt-core pull request #5563
Opened 2022-07-27 03:36 UTC by leahwicz

### Description
The changes simplify this workflow from it's first iteration:

1) It adds changelog generation
2) It scrubs whitespace auto-generated by running `bumpversion`
3) Removes the option to not be a dry run. Instead, we will always create a PR and defaults to creating a PR (right now let's make sure we have eyes on this change before automating this commit away, that can be in the larger Release workflow changes)

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

2022-07-27 15:07 UTC, emmyoop requested changes
This will be nice to automated!  Just a few suggestions.

2022-07-27 15:07 UTC, emmyoop commented on .github/workflows/version-bump.yml
>         description: 'The version number to bump to'
Can you add an example format here in parens?  Makes it easier to know if a dash should be included or not.

2022-07-28 02:13 UTC, leahwicz commented on .github/workflows/version-bump.yml
> +          git checkout -b bumping-version/${{ github.event.inputs.version_number }}_$GITHUB_RUN_ID
Done! Good suggestion!

2022-07-28 02:13 UTC, leahwicz commented on .github/workflows/version-bump.yml
> +            prerelease="${BASH_REMATCH[2]}"
Oh this is so much better than my crappy regex! Thanks!

2022-07-28 13:55 UTC, emmyoop approved these changes
Look good!

2022-07-28 18:08 UTC, merged