add -f for seeds
dbt-labs/dbt-core pull request #5991
Opened 2022-10-03 16:06 UTC by dave-connors-3

resolves #5990 

### Description

Seeds need `-f` too! 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/73915542/193625911-3d7aad85-8101-40df-b07a-9590f7767df8.png">

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2022-10-03 16:59 UTC, gshank approved these changes

2022-10-04 13:32 UTC, leahwicz commented
@jtcohen6 would we want this in the 1.3 release?

2022-10-04 13:56 UTC, jtcohen6 commented
@leahwicz Not worth the hassle / risk of backporting IMO. It will be good to have some exciting user-facing functionality in v1.4! Or we could include in the v1.3.1 patch if needed.

2022-10-05 20:35 UTC, emmyoop requested changes

2022-10-05 20:35 UTC, emmyoop commented on .changes/unreleased/Features-20221003-110705.yaml
> +body: extend -f
Can you expand this to be a bit more specific on what's being added.  A user should be able to read the changelog message and know generally what's been updated.

```suggestion
body: extend -f flag shorthand for seed command
```

2022-10-05 21:13 UTC, emmyoop approved these changes

2022-10-05 21:13 UTC, emmyoop commented
Thanks @dave-connors-3!

2022-10-05 21:13 UTC, merged