Fix typo in util.py
dbt-labs/dbt-core pull request #6037
Opened 2022-10-10 13:48 UTC by eltociear

### Description

identifer -> identifier

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2022-10-20 06:04 UTC, eltociear commented
I signed CLA.

2022-10-27 01:42 UTC, leahwicz commented
@cla-bot check

2022-11-17 11:39 UTC, jtcohen6 commented
@eltociear Thanks for the PR! We wouldn't normally require a changelog entry for changes to non-functional code, but we also want to give you credit for the contribution :) think you could [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry) and push it up?

2022-11-18 14:07 UTC, emmyoop requested changes
Update the changelog and this should be good to go!  Thanks for the contribution.

2022-11-18 14:07 UTC, emmyoop commented on .changes/unreleased/Fixes-20221117-220320.yaml
> +  Issue: "6037"
We use a specific issue for changes that do not have associated issues.  It's the result of how our changelog is currently implemented.
```suggestion
  Issue: "4904"
```

2022-12-20 02:01 UTC, emmyoop approved these changes

2022-12-20 02:01 UTC, merged