convert 027 cycle test
dbt-labs/dbt-core pull request #6094
Opened 2022-10-18 19:46 UTC by MichelleArk

resolves #6093

### Description
- converts 027_cycle_tests to pytest

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2022-10-20 18:14 UTC, stu-k approved these changes

2022-10-20 18:19 UTC, emmyoop requested changes

2022-10-20 18:19 UTC, emmyoop commented on tests/functional/cycles/test_cycles.py
> +    def test_postgres_simple_cycle(self, project):
you need to remove the postgres in the test name

2022-10-20 18:19 UTC, emmyoop commented on tests/functional/cycles/test_cycles.py
> +    def test_postgres_complex_cycle(self, project):
same thing here

2022-10-21 14:18 UTC, emmyoop approved these changes
🎉  Looks good!

2022-10-21 15:41 UTC, merged