CT 1443 remove root path
dbt-labs/dbt-core pull request #6172
Opened 2022-10-28 14:47 UTC by gshank

resolves #6171

### Description

As part of cleanup for the structured logging effort, remove the 'root_path' field from most nodes.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2022-10-31 18:29 UTC, emmyoop requested changes
A few schema comments

2022-10-31 18:29 UTC, emmyoop commented on schemas/dbt/run-results/v4.json
> +          "default": "1.4.0a1"
It looks like only the default and description fields are changing.  Do we really need to commit this?

2022-10-31 18:29 UTC, emmyoop commented on schemas/dbt/manifest/v7.json
> -        },
Do we need to bump the schema to v8 instead of modifying?

2022-11-04 15:45 UTC, gshank commented
Yes, we did need to bump the schema to v8. Have done that work.

2022-11-04 16:25 UTC, emmyoop requested changes
The run-results schema is just updating defaults and descriptions so `run-results/v4.json` should be removed from the PR.

2022-11-04 18:12 UTC, gshank commented
Yeah, I've removed that run-results file a couple of times and then I run the script again... Gone now, I hope.

2022-11-04 19:04 UTC, emmyoop approved these changes

2022-11-04 20:38 UTC, merged