Make use of hashlib.md5() FIPS compliant
dbt-labs/dbt-core pull request #6982
Opened 2023-02-15 11:35 UTC by nielspardon

resolves #6900

### Description

- replaces all direct usages of `hashlib.md5()` with calls to `dbt.utils.md5()`
- sets `usedforsecurity=False` when calling `hashlib.md5()`

Previously when running `make test` on a FIPS enabled system there were many test failures. With the changes of this PR both `make test` and `make integration` run through without errors on a FIPS enabled system.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2023-02-15 14:38 UTC, gshank requested changes
We're getting a bunch of:
```
    def md5(string, charset="utf-8"):
>       return hashlib.md5(string.encode(charset), usedforsecurity=False).hexdigest()
E       TypeError: openssl_md5() takes no keyword arguments
```

2023-02-15 14:42 UTC, gshank commented
It looks like that keyword parameter is only supported for Python 3.9 and later, so we'll have to check the python version when making those md5 calls.

2023-02-15 14:56 UTC, nielspardon commented
> It looks like that keyword parameter is only supported for Python 3.9 and later, so we'll have to check the python version when making those md5 calls.

Since I'm not a big Python expert. Do you have a suggestion / pattern for such cases already that I can use? Like checking the Python version and then only supplying the parameter if we run on >3.9?

2023-02-15 15:04 UTC, nielspardon commented
I'm guessing something like this should do the trick?

```python
def md5(string, charset="utf-8"):
    if sys.version_info >= (3, 9):
        return hashlib.md5(string.encode(charset), usedforsecurity=False).hexdigest()
    else:
        return hashlib.md5(string.encode(charset)).hexdigest()
```

2023-02-15 15:47 UTC, gshank commented
Yes, that's the right way to check python versions.

2023-02-15 15:50 UTC, nielspardon commented
I updated the PR. Since the `usedforsecurity` parameter was only added in Python 3.9 one can not run dbt on Python <3.9 with FIPS mode enabled.

I verified on a test system that tests are running fine with Python 3.8 when FIPS is deactivated with the if statement.

2023-02-15 16:22 UTC, gshank approved these changes

2023-02-15 16:22 UTC, merged

2023-02-16 10:51 UTC, jtcohen6 commented
Backporting for inclusion in next v1.4 patch (probably v1.4.3), per reasonable request: https://github.com/dbt-labs/dbt-core/issues/6900#issuecomment-1432765218