Adding link to 1.5 release notes
dbt-labs/dbt-core pull request #7700
Opened 2023-05-25 01:52 UTC by leahwicz

resolves #7671 

### Description
In cutting the release branch and cleaning up the changelog in `main`, we missed adding the 1.5 release notes link to the changie template here

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2023-05-25 02:47 UTC, dbeatty10 approved these changes

2023-05-25 15:28 UTC, emmyoop requested changes
Not sure if there's another PR targetting `main` but that's the only place this needs to be added.  Then if you run `changie merge` it will also update the CHANGELOG.md with the link.

2023-05-25 15:28 UTC, emmyoop commented on .changes/0.0.0.md
> +* [1.5](https://github.com/dbt-labs/dbt-core/blob/1.5.latest/CHANGELOG.md)
This is just linking back on itself.  This change is only needed in `main`.

2023-05-26 00:19 UTC, leahwicz commented
@emmyoop good catch! Thank you!
Closing this in favor of this PR https://github.com/dbt-labs/dbt-core/pull/7707

2023-05-26 00:19 UTC, closed without merging