Add implementation issue template
dbt-labs/dbt-core pull request #8176
Opened 2023-07-20 19:46 UTC by MichelleArk

resolves #  
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#  

### Problem

### Solution

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [ ] I have run this code in development and it appears to resolve the stated issue  
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

2023-07-20 19:57 UTC, ChenyuLInx approved these changes
Ship it!!!!

2023-07-20 20:12 UTC, nathaniel-may approved these changes

2023-07-20 21:21 UTC, emmyoop requested changes
No overall probl;ems with this but can we format it with the built in [form syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) so it's not just a blank page with headings pre-formatted but actual input boxes?  It will increase usage of the text areas instead of people just deleting them.  It's also easier to read.

2023-07-20 21:21 UTC, emmyoop commented on .github/ISSUE_TEMPLATE/implementation-ticket.md
> +Describe of the scope of the ticket, a high-level implementation approach and any tradeoffs to consider
```suggestion
Describe the scope of the ticket, a high-level implementation approach and any tradeoffs to consider
```

2023-07-21 17:46 UTC, emmyoop approved these changes

2023-07-21 17:50 UTC, merged