Update implementation-ticket.yml to change "Notion docs" to "documentations"
dbt-labs/dbt-core pull request #9316
Opened 2023-12-25 10:37 UTC by Tonayya

Changed "Notion docs" to "documentations"

resolves #

### Problem

### Solution

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [ ] I have run this code in development and it appears to resolve the stated issue  
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [ ] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

2024-01-04 17:11 UTC, emmyoop requested changes
Thanks for getting this up @Tonayya!  It's looking great.  Just a few more tweaks.

2024-01-04 17:11 UTC, emmyoop commented on .changes/unreleased/Docs-20231227-161008.yaml
No need for a changelog for every commit.  I would combine these together to just say something like "Updated the  format of the project to meet OSS standards at dbt Labs."

2024-01-04 17:11 UTC, emmyoop commented on .github/ISSUE_TEMPLATE/implementation-ticket.yml
> +        Provide the "why", motivation, and alternative approaches considered -- linking to previous refinement issues, spikes and documentations as appropriate
typo
```suggestion
        Provide the "why", motivation, and alternative approaches considered -- linking to previous refinement issues, spikes and documentation as appropriate
```

2024-01-04 17:11 UTC, emmyoop commented on CONTRIBUTING.md
> -
We should keep this section as it's specific to `dbt-core` and the 2 types of tests we use.

2024-01-04 17:11 UTC, emmyoop commented on CONTRIBUTING.md
> +## Troubleshooting Tips
The comment about the cla-bot should get moved into Troubleshooting tips.

2024-01-10 02:53 UTC, Tonayya commented
Hi @emmyoop I think this is now ready for your review :)

2024-01-12 15:09 UTC, emmyoop requested changes
Looking great!  Just a few tweaks.

2024-01-25 14:27 UTC, emmyoop requested changes
One more change!  Almost there.

2024-01-25 14:27 UTC, emmyoop commented on .github/ISSUE_TEMPLATE/implementation-ticket.yml
> +        required: false
This is still indented too much.  After you merge in your changes, you should view the file and it should render with text boxes.  Right now it shows an error at the top that this key isn't allowed.
```suggestion
    validations:
      required: false
```

2024-01-26 20:48 UTC, merged