Integration Test Optimizations
dbt-labs/dbt-core pull request #9499
Opened 2024-01-31 20:39 UTC by peterallenwebb

resolves #9498 

### Problem
 
Integration tests perform a lot of identical rework for every test.

### Solution

Cache important static objects between test runs.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

2024-01-31 20:45 UTC, gshank approved these changes

2024-01-31 22:28 UTC, colin-rogers-dbt requested changes
Blocking on validation this doesn't impact adapter expectations around macros/test fixtures: https://github.com/dbt-labs/dbt-snowflake/actions/runs/7733189834/job/21084750889

2024-01-31 22:29 UTC, colin-rogers-dbt commented on core/dbt/tests/fixtures/project.py
> +    enable_test_caching()
can we add a way to disable this if we want to?

2024-01-31 22:30 UTC, colin-rogers-dbt commented
does this result in test runs caching macros in ways that dbt-core wouldn't do typically? That seems to create a divergence between actual and test behavior of dbt-core

2024-01-31 22:38 UTC, colin-rogers-dbt commented
> Blocking on validation this doesn't impact adapter expectations around macros/test fixtures: https://github.com/dbt-labs/dbt-snowflake/actions/runs/7733189834/job/21084750889

Looks like it succeeded so it's probably good to go, will check a couple other adapters

2024-02-01 20:48 UTC, peterallenwebb commented
@colin-rogers-dbt I considered that, and wouldn't be doing this if it didn't save us a ton of testing time. With that said, the objects we are caching appear to be static after construction, and are computed as a pure function of their construction parameters. So while I can not completely rule out future complications without deeper knowledge of jinja internals, my sense is that complications are unlikely.

2024-02-01 21:39 UTC, colin-rogers-dbt approved these changes

2024-02-01 22:03 UTC, merged