fix: support python 3.12
dbt-labs/dbt-core pull request #9601
Opened 2024-02-20 07:23 UTC by l1xnan

### Problem

`distutils.util.strtobool` was removed in Python 3.12.1, see https://github.com/dbt-labs/dbt-core/issues/9007

### Solution

Copying the `distutils.util.strtobool` implementation from python 3.10.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

2024-02-20 14:12 UTC, seb-posedio requested changes

2024-02-20 14:12 UTC, seb-posedio commented on core/dbt/utils.py
> +        raise ValueError("invalid truth value %r" % (val,))
Missing newline

2024-02-20 14:31 UTC, l1xnan commented on core/dbt/utils.py
> +        raise ValueError("invalid truth value %r" % (val,))
Sorry, I've fixed it.

2024-02-21 14:35 UTC, aranke commented
Hey @l1xnan,

Thanks for the PR, it looks good to me!

Can you please sign the CLA and add a changelog entry so we can merge this in?
Instructions on creating a changelog entry are here: https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-or-modifying-a-changelog-entry

Thank you!

2024-02-23 08:40 UTC, l1xnan commented
Run `pip install -e dbt-core` in python 3.11, it is installed by running `setup.py develop`:
```
# lib/site-packages
dbt/
dbt-core.egg-link
easy-install.pth    # The content is `<project-root>/dbt-core/core`
```

As a comparison, run `pip install -e dbt-core` in python 3.12, `dbt-core` is installed by building it as a temp wheel file:
```
# lib/site-packages
dbt/
dbt_core-1.8.0a1.dist-info/
__editable___dbt_core_1_8_0a1_finder.py
__editable__.dbt_core-1.8.0a1
```
The `easy-install.pth` file is missing, `dbt.include.starter_project` is only found in the `site-packages/dbt`, so the `dbt.include.starter_project` cannot be imported.

2024-02-26 02:40 UTC, l1xnan commented
Official resolves

2024-02-26 02:40 UTC, closed without merging